import Head from "next/head";
import Image from "next/image";
import BaseLayout from "../components/core/layouts/BaseLayout";
import { ExtendedNextPage } from "../next";
import {
  IoSettingsOutline,
  IoDocumentTextOutline,
  IoAddOutline
} from "react-icons/io5";
import Card from "../components/core/Card";

const Home: ExtendedNextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen relative flex flex-col items-center justify-center sm:mx-auto mx-4">
        <div className="flex items-center justify-center">
          <input
            type="text"
            placeholder="Type here"
            className="input absolute top-12 w-full max-w-sm sm:max-w-xl lg:max-w-4xl input-bordered h-14 my-4 mt-8"
          />
        </div>

        <div className="flex w-full flex-wrap max-w-7xl justify-center items-center md:gap-8 sm:gap-6 gap-4">
          <Card title="Notes" Icon={IoDocumentTextOutline} theme="primary" />
          <Card title="New" Icon={IoAddOutline} theme="secondary" />
          <Card title="Settings" Icon={IoSettingsOutline} theme="accent" />
          {/* <div className="card lg:max-w-sm sm:max-w-[280px] max-w-sm w-full bg-secondary shadow-xl">
            <div className="card-body">
              <IoAddOutline size={96} className="text-primary mx-auto" />
              <h2 className="card-title text-primary mx-auto">New</h2>
            </div>
          </div> */}
          {/* <div className="card lg:max-w-sm sm:max-w-[280px] max-w-sm w-full bg-accent shadow-xl">
            <div className="card-body">
              <IoSettingsOutline size={96} className="text-base-200 mx-auto" />
              <h2 className="card-title text-base-200 mx-auto">Settings</h2>
            </div>
          </div> */}
        </div>
      </div>
    </div>
  );
};

Home.Layout = BaseLayout;

export default Home;
