import Head from "next/head";
import BaseLayout from "../components/core/layouts/BaseLayout";
import { ExtendedNextPage } from "../next";
import { IoSettingsOutline } from "@react-icons/all-files/io5/IoSettingsOutline";
import { IoDocumentTextOutline } from "@react-icons/all-files/io5/IoDocumentTextOutline";
import { IoAddOutline } from "@react-icons/all-files/io5/IoAddOutline";
import Card from "../components/core/Card";
import { useRef, useState } from "react";
import NewNoteModal from "../components/modals/NewNoteModal";

const Home: ExtendedNextPage = () => {
  const [open, setOpen] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  return (
    <>
      <Head>
        <title>Nonic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative flex flex-col items-center justify-center h-full mx-4 sm:mx-auto sm:mt-2">
        <div className="absolute top-0 z-10 items-center justify-center hidden w-full sm:flex">
          <input
            onClick={() => {
              setOpen((x) => !x);
            }}
            type="text"
            placeholder="Type here"
            className="w-full max-w-sm input modal-button sm:max-w-xl lg:max-w-4xl input-bordered h-14"
          />
        </div>
        <div className="flex flex-row flex-wrap items-center justify-center w-full gap-4 m-auto md:gap-8 sm:gap-6">
          <Card title="Notes" Icon={IoDocumentTextOutline} theme="primary" />
          <Card title="New" Icon={IoAddOutline} theme="secondary" />
          <Card title="Settings" Icon={IoSettingsOutline} theme="accent" />
        </div>
        {open && (
          <NewNoteModal inputRef={inputRef} onClose={() => setOpen(false)} />
        )}
      </div>
    </>
  );
};

Home.Layout = BaseLayout;

export default Home;
