import Head from "next/head";
import Image from "next/image";
import BaseLayout from "../components/core/layouts/BaseLayout";
import { ExtendedNextPage } from "../next";
import {
  IoSettingsOutline,
  IoDocumentTextOutline,
  IoAddOutline
} from "react-icons/io5";
import Card from "../components/core/Card";
import { useRef, useState } from "react";
import NewNoteModal from "../components/modals/NewNoteModal";

const Home: ExtendedNextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full relative flex flex-col items-center justify-center sm:mx-auto mt-6 sm:mt-0 mx-4">
        <div className="flex flex-row w-full flex-wrap justify-center items-center md:gap-8 sm:gap-6 gap-4">
          <Card title="Notes" Icon={IoDocumentTextOutline} theme="primary" />
          <Card title="New" Icon={IoAddOutline} theme="secondary" />
          <Card title="Settings" Icon={IoSettingsOutline} theme="accent" />
        </div>
      </div>
    </>
  );
};

Home.Layout = BaseLayout;

export default Home;
