import Head from "next/head";
import BaseLayout from "../components/core/layouts/BaseLayout";
import { ExtendedNextPage } from "../next";

import NoteCard from "../components/core/NoteCard";
import { GetStaticProps } from "next";
import { INote } from "../models/Note";

const NotesPage: ExtendedNextPage = ({ notes }) => {
  return (
    <>
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="sm:mt-36 mt-10" />
      <div className="flex sm:mx-auto mx-4 gap-6 flex-col flex-wrap sm:flex-row items-center justify-center">
        {notes?.map((x: INote) => {
          return <NoteCard key={x._id} note={x} />;
        })}
      </div>
    </>
  );
};

NotesPage.Layout = BaseLayout;

export default NotesPage;

export const getStaticProps: GetStaticProps = async (context) => {
  try {
    const res = await fetch(`${process.env.BASE_URL}/api`);
    const notes = await res.json();

    return {
      props: notes
    };
  } catch (error) {
    console.log(error);

    return {
      props: {} // will be passed to the page component as props
    };
  }
};
